### ISSUE TITLE
Can not start the project.

### ISSUE THREAD

**Issue by wangshuaidavid** [leanstacks/skeleton-ws-spring-boot#21]
***************************
APPLICATION FAILED TO START
***************************

Description:

Cannot determine embedded database driver class for database type NONE

Action:

If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (the profiles "hsqldb,batch" are currently active).

How to solve this problem? Thanks. :>

**Comment by mwarman** [comment]
The HSQLDB in-memory database, and the MySQL client JAR files are included in the Spring Boot Bill of Materials and, therefore, are automatically downloaded by Spring Boot as a part of a Maven or Gradle build.  You should not explicitly include those packages in your build scripts.

Simply use *either* the `hsqldb` *or* the `mysql` profile in the `application.properties` file, but not both.
