### ISSUE TITLE
Health actuator dont explose full information sur SYS_ADMIN

### ISSUE THREAD

**Issue by matdurand** [leanstacks/skeleton-ws-spring-boot#8]
The security config restrict the the actuators to the role SYSADMIN, but by default, springboot will look for the role ADMIN to display the full info in the health display. The property management.security.roles can be set to override the default ADMIN value.

Right now out of the box we only get {status: up}, and not the full info.

**Comment by mwarman** [comment]
Added `management.security.roles` property to `application.properties`.
